<template>
  <div class="container mt-4">
    <!-- タイトル部分 -->
    <TitleWrapper :title="pageTitle" :subtitle="pageSubtitle" />


    <!-- キャラクターリスト -->
    <div class="row">
      <CharacterCard
        v-for="character in sortedCharacters"
        :key="character.rank"
        :character="character"  
        class="col-12 mb-4"
        @click="selectCharacter(character)"  
      />
    </div>
    <div v-if="selectedCharacter" class="mt-4">
      <TitleWrapper :title="'Selected Character: ' + selectedCharacter.name" />
      <CharacterCard :character="selectedCharacter" />
    </div>
  </div>
</template>



<script setup>

const pageTitle = ref('僕のヒーローアカデミア キャラランキング');
const pageSubtitle = ref('魅力的なキャラたち、ここに集結！');


const selectedCharacter = ref(null);


const characters = [
{
    rank: 1,
    name: "爆豪勝己",
    heroName: "大・爆・殺・神ダイナマイト",
    ability: "爆破",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "折寺中学校",
    birthday: "4月20日",
    height: "172cm",
    bloodType: "A型",
    likes: "辛い食べ物全般、登山",
    personality: "暴言自信家",
    image:"/img/ばくごう.jpg",
  },
  {
    rank: 8,
    name: "轟燈矢",
    villainName: "荼毘",
    ability: "蒼炎",
    school: "-",
    formerSchool: "-",
    birthday: "1月18日",
    height: "176cm",
    bloodType: "-",
    likes: "蕎麦",
    personality: "つかめない",
    image: "/img/dabi.jpg",
  },
  {
    rank: 2,
    name: "緑谷出久",
    heroName: "デク",
    ability: "ワン・フォー・オール",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "折寺中学校",
    birthday: "7月15日",
    height: "166cm",
    bloodType: "O型",
    likes: "カツ丼、ヒーロー分析ノート",
    personality: "真面目で努力家",
    image: "/img/deku.jpg",
  },
  {
    rank: 3,
    name: "轟焦凍",
    heroName: " ショート",
    ability: "半冷半熱",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "凝山中学校",
    birthday: "1月11日",
    height: " 176cm",
    bloodType: "O型",
    likes: "蕎麦（温かくないやつ）",
    personality: "クール＆ホットな天然",
    image: "/img/shoto.jpg",
  },
  {
    rank: 4,
    name: "相澤消太",
    heroName: "抹消ヒーローイレイザーヘッド",
    ability: "抹消",
    school: "-",
    formerSchool:"-",
    birthday: "11月8日",
    height: "183cm",
    bloodType: "B型",
    likes: "ねこ",
    personality: "なんだかんだあまい",
    image: "/img/aizawa.jpg",
  },
  {
    rank: 5,
    name: "切島鋭児郎",
    heroName: "剛健ヒーロー烈怒頼雄斗",
    ability: "硬化",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "結田付中学校",
    birthday: "10月16日",
    height: "170cm<",
    bloodType: "O型",
    likes: "硬派な物、肉",
    personality: "快活ムードメーカー",
    image: "/img/kirishima.jpg",
  },
  {
    rank: 6,
    name: "轟炎司",
    heroName: "フレイムヒーローエンデヴァー",
    ability: "ヘルフレイム",
    school:"-",
    formerSchool:"-",
    birthday: "8月8日",
    height: "195cm",
    bloodType: "AB型",
    likes: "葛餅",
    personality: "頑固オヤジ",
    image: "/img/enn.jpg",
  },
  {
    rank: 7,
    name: "鷹見啓悟",
    heroName: "ウィングヒーローホークス",
    ability: "剛翼",
    school:"-",
    formerSchool:"-",
    birthday: "12月28日",
    height: "172cm",
    bloodType: "B型",
    likes: "鶏肉",
    personality: "目聡く耳聡い",
    image: "/img/hokusu.jpg",
  },
  {
    rank: 9,
    name: "志村転弧",
    villainName: "死柄木弔",
    ability: "崩壊",
    school: "-",
    formerSchool:"-",
    birthday: "4月4日",
    height: "175cm",
    bloodType:"-",
    likes: "ゲーム",
    personality: "子ども大人",
    image: "/img/shigaraki.jpg",
  },
  {
    rank: 10,
    name: "物間寧人",
    heroName: "ファントムシーフ",
    ability: "コピー",
    school: "雄英高校ヒーロー科1年B組",
    formerSchool: "逢沿中学校",
    birthday: "5月13日",
    height: "170cm",
    bloodType: "A型",
    likes: "フランス料理、バンド・デシネ",
    personality: "身内には優しい",
    image: "/img/monoma.jpg",
  },
  {
    rank: 11,
    name: "麗日お茶子",
    heroName: "ウラビティ",
    ability: "無重力",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "露座柳中学校",
    birthday: "12月27日",
    height: "156cm",
    bloodType: "B型",
    likes: "星空、和食",
    personality: "いつも麗らか",
    image: "/img/urara.jpg",
  },
  {
    rank: 12,
    name: "八木俊典",
    heroName: "オールマイト",
    ability: "ワン・フォー・オール",
    school:"-",
    formerSchool:"-",
    birthday: "6月10日",
    height: "220cm",
    bloodType: "A型",
    likes: "屋久杉・映画",
    personality: "意外とお茶目",
    image: "/img/oruma.jpg",
  },
  {
    rank: 13,
    name: "渡我被身子",
    villainName: "トガヒミコ",
    ability: "変身",
    school: "-",
    formerSchool: "-",
    birthday: "8月7日",
    height: "157cm",
    bloodType: "-",
    likes: "血、柘榴",
    personality: "惚れっぽい",
    image: "/img/toga.jpg",
  }, 
  {
    rank: 14,
    name: "上鳴電気",
    heroName: "スタンガンヒーローチャージズマ",
    ability: "帯電",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "谷便第一中学校",
    birthday: "6月29日",
    height: "168㎝",
    bloodType: "O型",
    likes: "流行ってるもの、ハンバーガー",
    personality: "チャラい系男子",
    image: "/img/kami.jpg",
  },
  {
    rank: 15,
    name: "心操人使",
    heroName: "-",
    ability: "洗脳",
    school: "雄英高校普通科1年C組",
    formerSchool: "名部中学校",
    birthday: "7月1日",
    height: "177cm",
    bloodType: "AB型",
    likes: "猫 、サイクリング",
    personality: "ストイック",
    image: "/img/mono.jpg",
  },
  {
    rank: 16,
    name: "天喰環",
    heroName: "サンイーター",
    ability: "再現",
    school: "雄英高校ヒーロー科3年A組",
    formerSchool: "-",
    birthday: "3月4日",
    height: "177cm",
    bloodType: "AB型",
    likes: "蝶",
    personality: "ネガティブ能力マン",
    image: "/img/sann.jpg",
  },
  {
    rank: 17,
    name: "ロディ・ソウル",
    heroName:"-",
    ability: "魂",
    school: "-",
    formerSchool: "-",
    birthday: "2月13日",
    height: "174cm",
    bloodType: "-",
    likes: "-",
    personality:"お調子者",
    image: "/img/rodhi.jpg",
  },
  {
    rank: 18,
    name: "飯田天哉",
    heroName: "インゲニウム",
    ability: "エンジン",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "聡明中学校",
    birthday: "8月22日",
    height: "179cm",
    bloodType: "A型",
    likes: "勉強、ビーフシチュー",
    personality: "委員長気質",
    image: "/img/iida.jpg",
  },
  {
    rank: 19,
    name: "常闇踏陰",
    heroName: "漆黒ヒーローツクヨミ",
    ability: "黒影",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "円扉中学校",
    birthday: "10月30日",
    height: "158㎝",
    bloodType: "AB型",
    likes: "リンゴ、薄暗い所",
    personality: "深淵を好むクール系",
    image: "/img/toko.jpg",
  },
  {
    rank: 20,
    name: "耳郎響香",
    heroName: "ヒアヒーローイヤホン=ジャック",
    ability: "イヤホンジャック",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "辺須瓶中学校",
    birthday: "8月1日",
    height: "154cm",
    bloodType: "A型",
    likes: "ロック",
    personality: "恥ずかしがり屋",
    image: "/img/iya.jpg",
  },
  {
    rank: 21,
    name: "通形ミリオ",
    heroName: "ルミリオン",
    ability: "透過",
    school: "雄英高校ヒーロー科3年B組",
    formerSchool: "-",
    birthday: "7月15日",
    height: "181cm",
    bloodType: "O型",
    likes: "ラーメン、お笑い",
    personality: "太陽的存在",
    image: "/img/miri.jpg",
  },
  {
    rank: 22,
    name: "八百万百",
    heroName: "万物ヒーロークリエティ",
    ability: "創造",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool:"掘須磨大付属中学校",
    birthday: "9月23日",
    height: "173cm",
    bloodType: "A型",
    likes: "読書（図鑑などを好む）",
    personality: "たまにポンコツ",
    image: "/img/yao.jpg",
  },
  {
    rank: 23,
    name: "兎山ルミ",
    heroName: "ラビットヒーローミルコ",
    ability: "兎",
    school:"-",
    formerSchool: "-",
    birthday: "3月1日",
    height: "159cm",
    bloodType: "O型",
    likes: "にんじん",
    personality: "男勝り",
    image: "/img/miru.jpg",
  },
  {
    rank: 24,
    name: "瀬呂範太",
    heroName: "テーピンヒーローセロファン",
    ability: "テープ",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool:"猿架舞中学校",
    birthday: "7月28日",
    height: "177cm",
    bloodType: "B型",
    likes: "健康に良い食べ物",
    personality: "空気読めるマン",
    image: "/img/sero.jpg",
  },
  {
    rank: 25,
    name: "山田ひざし",
    heroName: "ボイスヒーロープレゼント・マイク",
    ability: "ヴォイス",
    school: "-",
    formerSchool: "-",
    birthday: "7月7日",
    height: "185cm",
    bloodType: "B型",
    likes: "ラジオ、TV",
    personality: "ハイテンション",
    image: "/img/yamada.jpg",
  },
  {
    rank: 26,
    name: "蛙吹梅雨",
    heroName: "梅雨入りヒーローFROPPY",
    ability: "蛙",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool:"塩ノ洲中学校",
    birthday: "2月12日",
    height: "150cm",
    bloodType: "B型",
    likes: "雨 、ゼリー",
    personality: "友達想いの冷静淑女",
    image: "/img/asui.jpg",
  },
  {
    rank: 27,
    name: "青山優雅",
    heroName: "輝きヒーローCan't stop twinkling.",
    ability: "ネビルレーザー",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool:"聖カミイノ中学校",
    birthday: "5月30日",
    height: "168cm",
    bloodType: "O型",
    likes: "己",
    personality: "ナルシストな自由人",
    image: "/img/aoyama.jpg",
  },
  {
    rank: 28,
    name: "障子目蔵",
    heroName: "触手ヒーローテンタコル",
    ability: "複製腕",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool:"歌葉雨中学校",
    birthday: "2月15日",
    height: "187cm",
    bloodType: "B型",
    likes: "たこ焼き、イカスミパスタ",
    personality: "寡黙な紳士",
    image: "/img/tenn.jpg",
  },
  {
    rank: 29,
    name: "波動ねじれ",
    heroName: "ネジレチャン",
    ability: "波動",
    school: "雄英高校ヒーロー科3年A組",
    formerSchool: "-",
    birthday: "10月6日",
    height: "164cm",
    bloodType: "B型",
    likes: "ユリの花、ジャスミンティー",
    personality: "好奇心旺盛",
    image: "/img/neji.jpg",
  },
  {
    rank: 30,
    name: "袴田維",
    heroName: "ファイバーヒーローベストジーニスト",
    ability: "ファイバーマスター",
    school: "-",
    formerSchool: "-",
    birthday: "10月5日",
    height: "190cm",
    bloodType: "AB型",
    likes: "狼",
    personality: "何事もビッチリ",
    image: "/img/besu.jpg",
  },
  {
    rank: 31,
    name: "分倍河原仁",
    villainName: "トゥワイス",
    ability: "二倍",
    school: "-",
    formerSchool: "-",
    birthday: "5月10日",
    height: "178cm",
    bloodType:"O型",
    likes: "煙草",
    personality: "支離滅裂",
    image: "/img/twu.jpg",
  },
  {
    rank: 32,
    name: "筒美火伊那",
    villainName: "レディ・ナガン",
    ability: "ライフル / エアウォーク",
    school: "-",
    formerSchool: "-",
    birthday: "10月10日",
    height: "171cm",
    bloodType: "-",
    likes: "キレイなもの、かわいいもの",
    personality:"勝気で男勝り",
    image: "/img/re.jpg",
  },
  {
    rank: 33,
    name: "芦戸三奈",
    heroName: "pinky",
    ability: "酸",
    school:"雄英高校ヒーロー科1年A組",
    formerSchool:"結田付中学校",
    birthday: "7月30日",
    height: "159cm",
    bloodType: "AB型",
    likes: "ダンス、納豆、オクラ、恋バナ",
    personality: "元気100%",
    image: "/img/ashi.jpg",
  },
  {
    rank: 34,
    name: "灰廻航一",
    heroName: "ザ・スカイクロウラー",
    ability: "飛行",
    school: "-",
    formerSchool: "-",
    birthday: "2月22日",
    height: "172cm",
    bloodType:"-",
    likes: "カレー",
    personality: "気弱で温厚",
    image: "/img/hai.jpg",
  },
  {
    rank: 35,
    name: "尾白猿夫",
    heroName: "武闘ヒーローテイルマン",
    ability: "尻尾",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "舞木戸中学校",
    birthday: "5月28日",
    height: "169cm",
    bloodType:"O型",
    likes: "武術",
    personality: "普通に努力家",
    image: "/img/oji.jpg",
  },
  {
    rank: 36,
    name: "治埼廻",
    villainName: "オーバーホール",
    ability: "オーバーホール",
    school:"-",
    formerSchool:"-",
    birthday: "3月20日",
    height: "179cm",
    bloodType: "-",
    likes: "組",
    personality: "潔癖症",
    image: "/img/tisaki.jpg",
  },
  {
    rank: 37,
    name: "迫圧紘",
    villainName: "Mr.コンプレス",
    ability: "圧縮",
    school:"-",
    formerSchool:"-",
    birthday: "10月8日",
    height: "181cm",
    bloodType: "-",
    likes: "マジック",
    personality: "エンターテイナー",
    image: "/img/迫圧紘.jpg",
  },
  {
    rank: 38,
    name: "死柄木",
    villainName: "オール・フォー・ワン",
    ability: "オール・フォー・ワン",
    school:"-",
    formerSchool:"-",
    birthday: "-",
    height: "225cm",
    bloodType: "-",
    likes: "-",
    personality: "不気味",
    image: "/img/オールフォーワン.jpg",
  },
  {
    rank: 39,
    name: "紙原伸也",
    heroName: "忍者ヒーローエジショット",
    ability: "紙肢",
    school: "-",
    formerSchool: "-",
    birthday: "2月22日",
    height: "170cm",
    bloodType:"A型",
    likes: "忍者",
    personality: "-",
    image: "/img/エッジショット.jpg",
  },
  {
    rank: 40,
    name: "豊満太志郎",
    heroName: "BMIヒーローファットガム",
    ability: "脂肪吸着",
    school: "-",
    formerSchool: "-",
    birthday: "8月8日",
    height: "250cm",
    bloodType:"O型",
    likes: "たこ焼き",
    personality: "頼れる兄貴分",
    image: "/img/ファットガム.jpg",
  },
  {
    rank: 41,
    name: "壊理",
    heroName: "-",
    ability: "巻き戻し",
    school: "-",
    formerSchool: "-",
    birthday: "12月21日",
    height: "110cm",
    bloodType:"-",
    likes: "りんご",
    personality: "-",
    image: "/img/eri.jpg",
  },
  {
    rank: 42,
    name: "葉隠透",
    heroName: "ステルスヒーローインビジブルガール",
    ability: "透明化",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "毛糸中学校",
    birthday: "6月16日",
    height: "152cm",
    bloodType:"A型",
    likes: "キャラメル",
    personality: "すごく明るい",
    image: "/img/hagakure.jpg",
  },
  {
    rank: 43,
    name: "峰田実",
    heroName: "もぎたてヒーローGRAPEJUOICE",
    ability: "もぎもぎ",
    school: "雄英高校ヒーロー科1年A組",
    formerSchool: "笹木山中学校",
    birthday: "10月8日",
    height: "108cm",
    bloodType:"A型",
    likes: "女性",
    personality: "スケベ一直線",
    image: "/img/mineta.jpg",
  },
  {
    rank: 44,
    name: "飛田弾柔郎",
    villainName: "ジェントル・クリミナル",
    ability: "弾性",
    school: "-",
    formerSchool: "-",
    birthday: "8月29日",
    height: "181cm",
    bloodType: "A型",
    likes: "紅茶",
    personality:"ジェントルマン",
    image: "/img/jenntoru.jpg",
  },
  {
    rank: 45,
    name: "発目明",
    heroName: "-",
    ability: "ズーム",
    school: "雄英高校サポート科1年H組",
    formerSchool: "-",
    birthday: "4月18日",
    height: "157cm",
    bloodType:"O型",
    likes: "スチームパンク",
    personality: "チャレンジャー",
    image: "/img/hatume.jpg",
  },
  {
    rank: 46,
    name: "玄野針",
    villainName: "クロノスタシス",
    ability: "クロノスタシス",
    school: "-",
    formerSchool: "-",
    birthday: "-",
    height: "-",
    bloodType: "-",
    likes: "-",
    personality:"動じない",
    image: "/img/玄野針.jpg",
  },
  {
    rank: 47,
    name: "白雲朧",
    villainName: "黒霧",
    ability: "ワープゲート",
    school: "-",
    formerSchool: "-",
    birthday: "-",
    height: "-",
    bloodType: "-",
    likes: "-",
    personality:"冷静沈着",
    image: "/img/kurogiri.jpg",
  },
  {
    rank: 48,
    name: "佐々木未来",
    heroName: "サー・ナイトアイ",
    ability: "予知",
    school: "-",
    formerSchool: "-",
    birthday: "1月2日",
    height: "200cm",
    bloodType:"AB型",
    likes: "オールマイト、ヒーロー",
    personality: "ユーモア第一",
    image: "/img/sa-naitoai.jpg",
  },
  {
    rank: 49,
    name: "死柄木与一",
    heroName: "-",
    ability: "個性付与",
    school: "-",
    formerSchool: "-",
    birthday: "-",
    height: "-",
    bloodType:"-",
    likes: "-",
    personality: "-",
    image: "/img/yoiti.jpg",
  },
  {
    rank: 50,
    name: "駆藤",
    heroName: "-",
    ability: "変速",
    school: "-",
    formerSchool: "-",
    birthday: "-",
    height: "-",
    bloodType:"-",
    likes: "-",
    personality: "-",
    image: "/img/駆藤.jpg",
  },
];

const sortedCharacters = computed(() => {
  return [...characters].sort((a, b) => a.rank - b.rank); // ランク順
});

</script>